Upgrade Decidim to 0.23-stable
AjuntamentdeSantCugat/decidim-sant_cugat pull request #86
Opened 2020-12-09 14:37 UTC by ivan-mr

#### :tophat: What? Why?
Upgrade Decidim gem to 0.23-stable

#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [x] Subtask 1
- [ ] Subtask 2

### :camera: Screenshots (optional)

#### :ghost: GIF
![]()

2020-12-09 16:22 UTC, tramuntanal approved these changes
@ivan-mr can you link the changelog's of 0.23 in the description of this PR and check if there are any upgrade notes to be taken into account before merging?

2020-12-09 16:29 UTC, ivan-mr commented
> @ivan-mr can you link the changelog's of 0.23 in the description of this PR and check if there are any upgrade notes to be taken into account before merging?

Yes, I just changed it.
Thanks

2020-12-10 09:00 UTC, tramuntanal requested changes
@ivan-mr from the upgrade notes: "it is highly recommended to define your maps configuration with the new style", can you check it and the Ruby version please?

2020-12-11 10:31 UTC, victorol1 approved these changes

2020-12-11 10:43 UTC, merged